package main

import (
	"bufio"
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"math"
	"net/http"
	"os"
	"strings"
	"time"
)

// RescueTimePayload represents the data structure for RescueTime API (legacy offline time API)
type RescueTimePayload struct {
	StartTime       string `json:"start_time"`       // YYYY-MM-DD HH:MM:SS format
	Duration        int    `json:"duration"`         // duration in minutes
	ActivityName    string `json:"activity_name"`    // application class
	ActivityDetails string `json:"activity_details"` // window title/details
}

// UserClientEventPayload represents the native RescueTime user_client_events API format
type UserClientEventPayload struct {
	UserClientEvent UserClientEvent `json:"user_client_event"`
}

// UserClientEvent represents a single activity tracking event
type UserClientEvent struct {
	EventDescription string `json:"event_description"` // application class
	StartTime        string `json:"start_time"`        // RFC 3339 format: 2025-09-30T12:00:00Z
	EndTime          string `json:"end_time"`          // RFC 3339 format: 2025-09-30T12:01:00Z
	WindowTitle      string `json:"window_title"`      // window title
	Application      string `json:"application"`       // application class (redundant with event_description)
}

// ActivationRequest represents the payload for the /activate endpoint
type ActivationRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// ActivationResponse represents the response from the /activate endpoint
type ActivationResponse struct {
	AccountKey string `json:"account_key"`
	DataKey    string `json:"data_key"`
	ApiURL     string `json:"api_url"`
	URL        string `json:"url"`
}

// activateWithRescueTime authenticates with RescueTime and retrieves account keys
func activateWithRescueTime(email, password string) (*ActivationResponse, error) {
	// Discovered through testing: endpoint uses form-encoded data with username/password fields
	url := "https://api.rescuetime.com/activate"

	// Create form-encoded payload
	formData := fmt.Sprintf("username=%s&password=%s",
		strings.ReplaceAll(email, "@", "%40"), // URL encode @ sign
		password)

	// Create request
	req, err := http.NewRequest("POST", url, strings.NewReader(formData))
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %v", err)
	}

	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	req.Header.Set("User-Agent", "RescueTime/2.16.5.1 (Linux)")

	// Send request
	client := &http.Client{Timeout: 10 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("request failed: %v", err)
	}
	defer resp.Body.Close()

	// Read response
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response: %v", err)
	}

	// Check for error in response
	// Response format is YAML-like: "c:\n- 0\n- RT:ok\naccount_key: xxx\nkey: xxx"
	bodyStr := string(body)
	if strings.Contains(bodyStr, "RT:error") {
		return nil, fmt.Errorf("activation failed: %s", bodyStr)
	}

	// Parse response to extract account_key
	// TODO: The response only contains account_key, not data_key
	// We need to discover how to obtain the data_key (separate endpoint? different auth flow?)
	var accountKey string
	for _, line := range strings.Split(bodyStr, "\n") {
		if strings.HasPrefix(line, "account_key:") {
			accountKey = strings.TrimSpace(strings.TrimPrefix(line, "account_key:"))
			break
		}
	}

	if accountKey == "" {
		return nil, fmt.Errorf("no account_key in response: %s", bodyStr)
	}

	// Return response with account_key
	// Note: data_key is empty - needs further investigation
	return &ActivationResponse{
		AccountKey: accountKey,
		DataKey:    "", // TODO: Discover how to obtain data_key
		ApiURL:     "api.rescuetime.com",
		URL:        "www.rescuetime.com",
	}, nil
}

// saveCredentialsToEnv saves the activation credentials to .env file
func saveCredentialsToEnv(filepath string, response *ActivationResponse) error {
	// Read existing .env file to preserve RESCUE_TIME_API_KEY if it exists
	existingVars := make(map[string]string)

	file, err := os.Open(filepath)
	if err == nil {
		// File exists, read it
		scanner := bufio.NewScanner(file)
		for scanner.Scan() {
			line := strings.TrimSpace(scanner.Text())
			if line == "" || strings.HasPrefix(line, "#") {
				continue
			}
			parts := strings.SplitN(line, "=", 2)
			if len(parts) == 2 {
				existingVars[strings.TrimSpace(parts[0])] = strings.TrimSpace(parts[1])
			}
		}
		file.Close()
	}

	// Update with new credentials
	existingVars["RESCUE_TIME_ACCOUNT_KEY"] = response.AccountKey
	existingVars["RESCUE_TIME_DATA_KEY"] = response.DataKey

	// Write back to file
	f, err := os.Create(filepath)
	if err != nil {
		return fmt.Errorf("failed to create .env file: %v", err)
	}
	defer f.Close()

	writer := bufio.NewWriter(f)

	// Write header
	fmt.Fprintln(writer, "# RescueTime API Credentials")
	fmt.Fprintln(writer, "# Generated by active-window")
	fmt.Fprintln(writer, "")

	// Write all variables
	for key, value := range existingVars {
		fmt.Fprintf(writer, "%s=%s\n", key, value)
	}

	return writer.Flush()
}

// loadEnvFile loads environment variables from a .env file
func loadEnvFile(filepath string) error {
	file, err := os.Open(filepath)
	if err != nil {
		return fmt.Errorf("failed to open .env file: %v", err)
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())

		// Skip empty lines and comments
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		// Split on first '=' sign
		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			continue
		}

		key := strings.TrimSpace(parts[0])
		value := strings.TrimSpace(parts[1])

		// Set environment variable
		os.Setenv(key, value)
	}

	if err := scanner.Err(); err != nil {
		return fmt.Errorf("error reading .env file: %v", err)
	}

	return nil
}

// summaryToPayload converts an ActivitySummary to RescueTimePayload format (legacy)
func summaryToPayload(summary ActivitySummary) RescueTimePayload {
	// Convert duration to minutes (rounded up)
	durationMinutes := int(math.Ceil(summary.TotalDuration.Minutes()))

	// Format start time as "YYYY-MM-DD HH:MM:SS"
	startTimeFormatted := summary.FirstSeen.Format("2006-01-02 15:04:05")

	return RescueTimePayload{
		StartTime:       startTimeFormatted,
		Duration:        durationMinutes,
		ActivityName:    summary.AppClass,
		ActivityDetails: summary.ActivityDetails,
	}
}

// summaryToUserClientEvent converts an ActivitySummary to UserClientEventPayload format
func summaryToUserClientEvent(summary ActivitySummary) UserClientEventPayload {
	// Calculate end time: start time + total duration
	endTime := summary.FirstSeen.Add(summary.TotalDuration)

	// Format timestamps in RFC 3339 (ISO 8601) format with UTC timezone
	startTimeFormatted := summary.FirstSeen.UTC().Format(time.RFC3339)
	endTimeFormatted := endTime.UTC().Format(time.RFC3339)

	return UserClientEventPayload{
		UserClientEvent: UserClientEvent{
			EventDescription: summary.AppClass,
			StartTime:        startTimeFormatted,
			EndTime:          endTimeFormatted,
			WindowTitle:      summary.ActivityDetails,
			Application:      summary.AppClass, // Same as EventDescription
		},
	}
}

// submitToRescueTime submits activity data to RescueTime API with retry logic (legacy offline time API)
func submitToRescueTime(apiKey string, payload RescueTimePayload) error {
	const maxRetries = 3
	const baseDelay = 1 * time.Second

	var lastErr error

	for attempt := 0; attempt < maxRetries; attempt++ {
		if attempt > 0 {
			// Exponential backoff: 1s, 2s, 4s
			delay := baseDelay * time.Duration(math.Pow(2, float64(attempt-1)))
			fmt.Printf("Retrying in %v... (attempt %d/%d)\n", delay, attempt+1, maxRetries)
			time.Sleep(delay)
		}

		// Convert payload to JSON
		jsonData, err := json.Marshal(payload)
		if err != nil {
			return fmt.Errorf("failed to marshal payload: %v", err)
		}

		// Create request
		url := fmt.Sprintf("https://www.rescuetime.com/anapi/offline_time_post?key=%s", apiKey)
		req, err := http.NewRequest("POST", url, bytes.NewBuffer(jsonData))
		if err != nil {
			lastErr = fmt.Errorf("failed to create request: %v", err)
			continue
		}

		req.Header.Set("Content-Type", "application/json")

		// Send request
		client := &http.Client{Timeout: 10 * time.Second}
		resp, err := client.Do(req)
		if err != nil {
			lastErr = fmt.Errorf("request failed: %v", err)
			continue
		}

		// Read response body
		body, _ := io.ReadAll(resp.Body)
		resp.Body.Close()

		// Check response status
		if resp.StatusCode >= 200 && resp.StatusCode < 300 {
			fmt.Printf("✓ Submitted to RescueTime: %s (%d min)\n", payload.ActivityName, payload.Duration)
			return nil
		}

		lastErr = fmt.Errorf("API returned status %d: %s", resp.StatusCode, string(body))

		// Don't retry on client errors (4xx)
		if resp.StatusCode >= 400 && resp.StatusCode < 500 {
			return lastErr
		}
	}

	return fmt.Errorf("failed after %d attempts: %v", maxRetries, lastErr)
}

// submitUserClientEvent submits activity data to native RescueTime user_client_events API
func submitUserClientEvent(apiKey string, payload UserClientEventPayload) error {
	const maxRetries = 3
	const baseDelay = 1 * time.Second

	var lastErr error
	var tryBearerAuth bool

	for attempt := 0; attempt < maxRetries; attempt++ {
		if attempt > 0 {
			// Exponential backoff: 1s, 2s, 4s
			delay := baseDelay * time.Duration(math.Pow(2, float64(attempt-1)))
			fmt.Printf("Retrying in %v... (attempt %d/%d)\n", delay, attempt+1, maxRetries)
			time.Sleep(delay)
		}

		// Convert payload to JSON
		jsonData, err := json.Marshal(payload)
		if err != nil {
			return fmt.Errorf("failed to marshal payload: %v", err)
		}

		var req *http.Request

		// Try Bearer token auth if query param auth failed with 401
		if tryBearerAuth {
			// Create request WITHOUT query parameter
			url := "https://api.rescuetime.com/api/resource/user_client_events"
			req, err = http.NewRequest("POST", url, bytes.NewBuffer(jsonData))
			if err != nil {
				lastErr = fmt.Errorf("failed to create request: %v", err)
				continue
			}
			// Use Bearer token authentication with data_key
			// The desktop app uses the data_key as the Bearer token
			dataKey := os.Getenv("RESCUE_TIME_DATA_KEY")
			if dataKey == "" {
				dataKey = apiKey // Fallback to provided API key
			}
			req.Header.Set("Authorization", fmt.Sprintf("Bearer %s", dataKey))

			// Also try adding account_key as a query parameter along with Bearer token
			accountKey := os.Getenv("RESCUE_TIME_ACCOUNT_KEY")
			if accountKey != "" {
				req.URL.RawQuery = fmt.Sprintf("key=%s", accountKey)
			}
		} else {
			// Try query parameter authentication first with account_key
			authKey := os.Getenv("RESCUE_TIME_ACCOUNT_KEY")
			if authKey == "" {
				authKey = apiKey
			}
			url := fmt.Sprintf("https://api.rescuetime.com/api/resource/user_client_events?key=%s", authKey)
			req, err = http.NewRequest("POST", url, bytes.NewBuffer(jsonData))
			if err != nil {
				lastErr = fmt.Errorf("failed to create request: %v", err)
				continue
			}
		}

		// Set headers matching the official app
		req.Header.Set("Content-Type", "application/json; charset=utf-8")
		req.Header.Set("User-Agent", "RescueTime/2.16.5.1 (Linux)")

		// Send request
		client := &http.Client{Timeout: 10 * time.Second}
		resp, err := client.Do(req)
		if err != nil {
			lastErr = fmt.Errorf("request failed: %v", err)
			continue
		}

		// Read response body
		body, _ := io.ReadAll(resp.Body)
		resp.Body.Close()

		// Check response status
		if resp.StatusCode >= 200 && resp.StatusCode < 300 {
			authMethod := "query parameter"
			if tryBearerAuth {
				authMethod = "Bearer token"
			}
			fmt.Printf("✓ Submitted to RescueTime via %s: %s (%s to %s)\n",
				authMethod,
				payload.UserClientEvent.Application,
				payload.UserClientEvent.StartTime,
				payload.UserClientEvent.EndTime)
			return nil
		}

		lastErr = fmt.Errorf("API returned status %d: %s", resp.StatusCode, string(body))

		// If we got 401 with query param auth, try Bearer token auth next
		if resp.StatusCode == 401 && !tryBearerAuth {
			fmt.Println("Query parameter auth failed (401), trying Bearer token authentication...")
			tryBearerAuth = true
			continue
		}

		// Don't retry on other client errors (4xx)
		if resp.StatusCode >= 400 && resp.StatusCode < 500 {
			return lastErr
		}
	}

	return fmt.Errorf("failed after %d attempts: %v", maxRetries, lastErr)
}

// submitActivitiesToRescueTime submits all activity summaries to RescueTime
// Attempts native user_client_events API first if credentials are available,
// falls back to offline_time_post API if native fails or credentials are missing.
func submitActivitiesToRescueTime(apiKey string, summaries map[string]ActivitySummary) {
	if len(summaries) == 0 {
		fmt.Println("No activities to submit.")
		return
	}

	// Check if we have native API credentials
	dataKey := os.Getenv("RESCUE_TIME_DATA_KEY")
	accountKey := os.Getenv("RESCUE_TIME_ACCOUNT_KEY")
	hasNativeCredentials := dataKey != "" || accountKey != ""

	fmt.Printf("\n=== Submitting %d activities to RescueTime ===\n", len(summaries))
	if hasNativeCredentials {
		fmt.Println("[INFO] Native API credentials detected, will try native API first with legacy fallback")
	} else {
		fmt.Println("[INFO] Using legacy offline time API (no native credentials found)")
	}

	successCount := 0
	failCount := 0
	nativeSuccessCount := 0
	legacyFallbackCount := 0

	for _, summary := range summaries {
		// Skip activities with a very short duration (< 1 minute)
		if summary.TotalDuration < time.Minute {
			continue
		}

		var err error
		usedFallback := false

		if hasNativeCredentials {
			// Try native API first
			fmt.Printf("[ATTEMPT] Trying native API for %s...\n", summary.AppClass)
			payload := summaryToUserClientEvent(summary)
			err = submitUserClientEvent(apiKey, payload)

			if err != nil {
				// Native API failed, log and try legacy fallback
				fmt.Fprintf(os.Stderr, "[WARN] Native API failed for %s: %v\n", summary.AppClass, err)
				fmt.Printf("[FALLBACK] Attempting legacy API for %s...\n", summary.AppClass)

				legacyPayload := summaryToPayload(summary)
				err = submitToRescueTime(apiKey, legacyPayload)
				usedFallback = true
			} else {
				nativeSuccessCount++
			}
		} else {
			// No native credentials, use legacy API directly
			payload := summaryToPayload(summary)
			err = submitToRescueTime(apiKey, payload)
		}

		if err != nil {
			fmt.Fprintf(os.Stderr, "✗ Failed to submit %s: %v\n", summary.AppClass, err)
			failCount++
		} else {
			successCount++
			if usedFallback {
				legacyFallbackCount++
			}
		}
	}

	fmt.Printf("\n=== Submission Summary ===\n")
	fmt.Printf("Total succeeded: %d, failed: %d\n", successCount, failCount)
	if hasNativeCredentials {
		fmt.Printf("Native API successes: %d\n", nativeSuccessCount)
		fmt.Printf("Legacy fallback successes: %d\n", legacyFallbackCount)
	}
}
