package main

import (
	"bufio"
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"log/slog"
	"math"
	"net/http"
	"os"
	"strings"
	"time"
)

// RescueTimePayload represents the data structure for RescueTime API (legacy offline time API)
type RescueTimePayload struct {
	StartTime       string `json:"start_time"`       // YYYY-MM-DD HH:MM:SS format
	Duration        int    `json:"duration"`         // duration in minutes
	ActivityName    string `json:"activity_name"`    // application class
	ActivityDetails string `json:"activity_details"` // window title/details
}

// UserClientEventPayload represents the native RescueTime user_client_events API format
type UserClientEventPayload struct {
	UserClientEvent UserClientEvent `json:"user_client_event"`
}

// UserClientEvent represents a single activity tracking event
type UserClientEvent struct {
	EventDescription string `json:"event_description"` // application class
	StartTime        string `json:"start_time"`        // RFC 3339 format: 2025-09-30T12:00:00Z
	EndTime          string `json:"end_time"`          // RFC 3339 format: 2025-09-30T12:01:00Z
	WindowTitle      string `json:"window_title"`      // window title
	Application      string `json:"application"`       // application class (redundant with event_description)
}

// ActivationRequest represents the payload for the /activate endpoint
type ActivationRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// ActivationResponse represents the response from the /activate endpoint
type ActivationResponse struct {
	AccountKey string `json:"account_key"`
	DataKey    string `json:"data_key"`
	ApiURL     string `json:"api_url"`
	URL        string `json:"url"`
}

// activateWithRescueTime authenticates with RescueTime and retrieves account keys
func activateWithRescueTime(email, password string) (*ActivationResponse, error) {
	// Discovered through testing: endpoint uses form-encoded data with username/password fields
	url := "https://api.rescuetime.com/activate"

	// Create form-encoded payload
	formData := fmt.Sprintf("username=%s&password=%s",
		strings.ReplaceAll(email, "@", "%40"), // URL encode @ sign
		password)

	// Create request
	req, err := http.NewRequest("POST", url, strings.NewReader(formData))
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %v", err)
	}

	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	req.Header.Set("User-Agent", "RescueTime/2.16.5.1 (Linux)")

	// Send request
	client := &http.Client{Timeout: 10 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("request failed: %v", err)
	}
	defer resp.Body.Close()

	// Read response
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response: %v", err)
	}

	// Check for error in response
	// Response format is YAML-like: "c:\n- 0\n- RT:ok\naccount_key: xxx\nkey: xxx"
	bodyStr := string(body)
	if strings.Contains(bodyStr, "RT:error") {
		return nil, fmt.Errorf("activation failed: %s", bodyStr)
	}

	// Parse response to extract account_key
	var accountKey string
	for _, line := range strings.Split(bodyStr, "\n") {
		if strings.HasPrefix(line, "account_key:") {
			accountKey = strings.TrimSpace(strings.TrimPrefix(line, "account_key:"))
			break
		}
	}

	if accountKey == "" {
		return nil, fmt.Errorf("no account_key in response: %s", bodyStr)
	}

	return &ActivationResponse{
		AccountKey: accountKey,
		DataKey:    "",
		ApiURL:     "api.rescuetime.com",
		URL:        "www.rescuetime.com",
	}, nil
}

// saveCredentialsToEnv saves the activation credentials to .env file
func saveCredentialsToEnv(filepath string, response *ActivationResponse) error {
	// Read existing .env file to preserve RESCUE_TIME_API_KEY if it exists
	existingVars := make(map[string]string)

	file, err := os.Open(filepath)
	if err == nil {
		// File exists, read it
		scanner := bufio.NewScanner(file)
		for scanner.Scan() {
			line := strings.TrimSpace(scanner.Text())
			if line == "" || strings.HasPrefix(line, "#") {
				continue
			}
			parts := strings.SplitN(line, "=", 2)
			if len(parts) == 2 {
				existingVars[strings.TrimSpace(parts[0])] = strings.TrimSpace(parts[1])
			}
		}
		file.Close()
	}

	// Update with new credentials
	existingVars["RESCUE_TIME_ACCOUNT_KEY"] = response.AccountKey
	existingVars["RESCUE_TIME_DATA_KEY"] = response.DataKey

	// Write back to file
	f, err := os.Create(filepath)
	if err != nil {
		return fmt.Errorf("failed to create .env file: %v", err)
	}
	defer f.Close()

	writer := bufio.NewWriter(f)

	// Write header
	fmt.Fprintln(writer, "# RescueTime API Credentials")
	fmt.Fprintln(writer, "# Generated by active-window")
	fmt.Fprintln(writer, "")

	// Write all variables
	for key, value := range existingVars {
		fmt.Fprintf(writer, "%s=%s\n", key, value)
	}

	return writer.Flush()
}

// loadEnvFile loads environment variables from a .env file
func loadEnvFile(filepath string) error {
	file, err := os.Open(filepath)
	if err != nil {
		return fmt.Errorf("failed to open .env file: %v", err)
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())

		// Skip empty lines and comments
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		// Split on first '=' sign
		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			continue
		}

		key := strings.TrimSpace(parts[0])
		value := strings.TrimSpace(parts[1])

		// Set environment variable
		os.Setenv(key, value)
	}

	if err := scanner.Err(); err != nil {
		return fmt.Errorf("error reading .env file: %v", err)
	}

	return nil
}

// summaryToPayload converts an ActivitySummary to RescueTimePayload format (legacy)
func summaryToPayload(summary ActivitySummary) RescueTimePayload {
	// Convert duration to minutes (rounded up)
	durationMinutes := int(math.Ceil(summary.TotalDuration.Minutes()))

	// Format start time as "YYYY-MM-DD HH:MM:SS"
	startTimeFormatted := summary.FirstSeen.Format("2006-01-02 15:04:05")

	return RescueTimePayload{
		StartTime:       startTimeFormatted,
		Duration:        durationMinutes,
		ActivityName:    summary.AppClass,
		ActivityDetails: summary.ActivityDetails,
	}
}

// summaryToUserClientEvent converts an ActivitySummary to UserClientEventPayload format
func summaryToUserClientEvent(summary ActivitySummary) UserClientEventPayload {
	// Calculate end time: start time + total duration
	endTime := summary.FirstSeen.Add(summary.TotalDuration)

	// Format timestamps in RFC 3339 (ISO 8601) format with UTC timezone
	startTimeFormatted := summary.FirstSeen.UTC().Format(time.RFC3339)
	endTimeFormatted := endTime.UTC().Format(time.RFC3339)

	return UserClientEventPayload{
		UserClientEvent: UserClientEvent{
			EventDescription: summary.AppClass,
			StartTime:        startTimeFormatted,
			EndTime:          endTimeFormatted,
			WindowTitle:      summary.ActivityDetails,
			Application:      summary.AppClass,
		},
	}
}

// submitToRescueTime submits activity data to RescueTime API with retry logic (legacy offline time API)
func submitToRescueTime(apiKey string, payload RescueTimePayload) error {
	const maxRetries = 3
	const baseDelay = 1 * time.Second

	var lastErr error

	for attempt := 0; attempt < maxRetries; attempt++ {
		if attempt > 0 {
			// Exponential backoff: 1s, 2s, 4s
			delay := baseDelay * time.Duration(math.Pow(2, float64(attempt-1)))
			slog.Debug("retrying legacy API submission",
				"delay", delay, "attempt", attempt+1, "max_attempts", maxRetries)
			time.Sleep(delay)
		}

		// Convert payload to JSON
		jsonData, err := json.Marshal(payload)
		if err != nil {
			return fmt.Errorf("failed to marshal payload: %v", err)
		}

		// Create request
		url := fmt.Sprintf("https://www.rescuetime.com/anapi/offline_time_post?key=%s", apiKey)
		req, err := http.NewRequest("POST", url, bytes.NewBuffer(jsonData))
		if err != nil {
			lastErr = fmt.Errorf("failed to create request: %v", err)
			continue
		}

		req.Header.Set("Content-Type", "application/json")

		// Send request
		client := &http.Client{Timeout: 10 * time.Second}
		resp, err := client.Do(req)
		if err != nil {
			lastErr = fmt.Errorf("request failed: %v", err)
			continue
		}

		// Read response body
		body, _ := io.ReadAll(resp.Body)
		resp.Body.Close()

		// Check response status
		if resp.StatusCode >= 200 && resp.StatusCode < 300 {
			slog.Info("submitted to RescueTime (legacy)",
				"app", payload.ActivityName, "duration_min", payload.Duration)
			return nil
		}

		lastErr = fmt.Errorf("API returned status %d: %s", resp.StatusCode, string(body))

		// Don't retry on client errors (4xx)
		if resp.StatusCode >= 400 && resp.StatusCode < 500 {
			return lastErr
		}
	}

	return fmt.Errorf("failed after %d attempts: %v", maxRetries, lastErr)
}

// submitUserClientEvent submits activity data to native RescueTime user_client_events API
func submitUserClientEvent(apiKey string, payload UserClientEventPayload) error {
	const maxRetries = 3
	const baseDelay = 1 * time.Second

	var lastErr error
	var tryBearerAuth bool

	for attempt := 0; attempt < maxRetries; attempt++ {
		if attempt > 0 {
			// Exponential backoff: 1s, 2s, 4s
			delay := baseDelay * time.Duration(math.Pow(2, float64(attempt-1)))
			slog.Debug("retrying native API submission",
				"delay", delay, "attempt", attempt+1, "max_attempts", maxRetries)
			time.Sleep(delay)
		}

		// Convert payload to JSON
		jsonData, err := json.Marshal(payload)
		if err != nil {
			return fmt.Errorf("failed to marshal payload: %v", err)
		}

		var req *http.Request

		// Try Bearer token auth if query param auth failed with 401
		if tryBearerAuth {
			url := "https://api.rescuetime.com/api/resource/user_client_events"
			req, err = http.NewRequest("POST", url, bytes.NewBuffer(jsonData))
			if err != nil {
				lastErr = fmt.Errorf("failed to create request: %v", err)
				continue
			}
			dataKey := os.Getenv("RESCUE_TIME_DATA_KEY")
			if dataKey == "" {
				dataKey = apiKey
			}
			req.Header.Set("Authorization", fmt.Sprintf("Bearer %s", dataKey))

			accountKey := os.Getenv("RESCUE_TIME_ACCOUNT_KEY")
			if accountKey != "" {
				req.URL.RawQuery = fmt.Sprintf("key=%s", accountKey)
			}
		} else {
			authKey := os.Getenv("RESCUE_TIME_ACCOUNT_KEY")
			if authKey == "" {
				authKey = apiKey
			}
			url := fmt.Sprintf("https://api.rescuetime.com/api/resource/user_client_events?key=%s", authKey)
			req, err = http.NewRequest("POST", url, bytes.NewBuffer(jsonData))
			if err != nil {
				lastErr = fmt.Errorf("failed to create request: %v", err)
				continue
			}
		}

		// Set headers matching the official app
		req.Header.Set("Content-Type", "application/json; charset=utf-8")
		req.Header.Set("User-Agent", "RescueTime/2.16.5.1 (Linux)")

		// Send request
		client := &http.Client{Timeout: 10 * time.Second}
		resp, err := client.Do(req)
		if err != nil {
			lastErr = fmt.Errorf("request failed: %v", err)
			continue
		}

		// Read response body
		body, _ := io.ReadAll(resp.Body)
		resp.Body.Close()

		// Check response status
		if resp.StatusCode >= 200 && resp.StatusCode < 300 {
			authMethod := "query parameter"
			if tryBearerAuth {
				authMethod = "Bearer token"
			}
			slog.Info("submitted to RescueTime (native)",
				"auth", authMethod,
				"app", payload.UserClientEvent.Application,
				"start", payload.UserClientEvent.StartTime,
				"end", payload.UserClientEvent.EndTime)
			return nil
		}

		lastErr = fmt.Errorf("API returned status %d: %s", resp.StatusCode, string(body))

		// If we got 401 with query param auth, try Bearer token auth next
		if resp.StatusCode == 401 && !tryBearerAuth {
			slog.Warn("query parameter auth failed, trying Bearer token",
				"status", resp.StatusCode)
			tryBearerAuth = true
			continue
		}

		// Don't retry on other client errors (4xx)
		if resp.StatusCode >= 400 && resp.StatusCode < 500 {
			return lastErr
		}
	}

	return fmt.Errorf("failed after %d attempts: %v", maxRetries, lastErr)
}

// SubmissionResult holds the outcome of a batch submission
type SubmissionResult struct {
	Succeeded      int
	Failed         int
	NativeSuccess  int
	LegacyFallback int
	Errors         []error
}

// submissionItem holds the result of a single activity submission
type submissionItem struct {
	err      error
	native   bool
	fallback bool
}

// submitActivitiesToRescueTime submits all activity summaries to RescueTime
// using bounded concurrency (3 goroutines). Attempts native API first if
// credentials are available, falls back to legacy API.
func submitActivitiesToRescueTime(apiKey string, summaries map[string]ActivitySummary) SubmissionResult {
	result := SubmissionResult{}

	if len(summaries) == 0 {
		slog.Debug("no activities to submit")
		return result
	}

	// Check if we have native API credentials
	dataKey := os.Getenv("RESCUE_TIME_DATA_KEY")
	accountKey := os.Getenv("RESCUE_TIME_ACCOUNT_KEY")
	hasNativeCredentials := dataKey != "" || accountKey != ""

	// Filter to submittable activities (>= 1 minute)
	var toSubmit []ActivitySummary
	for _, summary := range summaries {
		if summary.TotalDuration < time.Minute {
			slog.Debug("skipping short activity",
				"app", summary.AppClass, "duration", summary.TotalDuration)
			continue
		}
		toSubmit = append(toSubmit, summary)
	}

	if len(toSubmit) == 0 {
		slog.Debug("no activities above minimum duration")
		return result
	}

	slog.Info("starting submission", "activity_count", len(toSubmit),
		"native_credentials", hasNativeCredentials)

	// Bounded concurrency with semaphore channel
	const maxConcurrent = 3
	sem := make(chan struct{}, maxConcurrent)
	results := make(chan submissionItem, len(toSubmit))

	for _, summary := range toSubmit {
		sem <- struct{}{} // acquire
		go func(s ActivitySummary) {
			defer func() { <-sem }() // release

			item := submissionItem{}

			if hasNativeCredentials {
				slog.Debug("trying native API", "app", s.AppClass)
				payload := summaryToUserClientEvent(s)
				err := submitUserClientEvent(apiKey, payload)

				if err != nil {
					slog.Warn("native API failed, trying legacy fallback",
						"app", s.AppClass, "error", err)
					legacyPayload := summaryToPayload(s)
					err = submitToRescueTime(apiKey, legacyPayload)
					if err == nil {
						item.fallback = true
					} else {
						item.err = err
					}
				} else {
					item.native = true
				}
			} else {
				payload := summaryToPayload(s)
				if err := submitToRescueTime(apiKey, payload); err != nil {
					item.err = err
				}
			}

			results <- item
		}(summary)
	}

	// Collect results
	for range len(toSubmit) {
		item := <-results
		if item.err != nil {
			result.Failed++
			result.Errors = append(result.Errors, item.err)
		} else {
			result.Succeeded++
			if item.native {
				result.NativeSuccess++
			}
			if item.fallback {
				result.LegacyFallback++
			}
		}
	}

	slog.Info("submission complete",
		"succeeded", result.Succeeded, "failed", result.Failed,
		"native", result.NativeSuccess, "legacy_fallback", result.LegacyFallback)

	return result
}
